import { Button, SafeAreaView, SafeAreaViewBase, ScrollView, StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <SafeAreaView style={styles.safeArea}>
      {/* Uncomment the Text component */}
    <ScrollView contentContainerStyle={styles.scroll} horizontal>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      <Text>"helo"</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    display:"flex",
    // flexDirection:"row",
    paddingTop: 35,
    // // flex: 1, // Ensure SafeAreaView takes full screen
    // justifyContent: 'center', // Center content vertically
    // alignItems: 'center', // Center content horizontally
  },
  scroll: {
    display: 'flex',
    backgroundColor: 'red',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
 
});
